djangosite/djangosite/urls.py
# SPDX-FileCopyrightText: 2023 Galagic Limited, et al. <https://galagic.com>
#
# SPDX-License-Identifier: AGPL-3.0-or-later
#
# Self-hosted lists of any kind: wishlists, task lists, collections and more.
#
# For full copyright information see the AUTHORS file at the top-level
# directory of this distribution or at
# [AUTHORS](https://gitlab.com/thegalagic/listidge/AUTHORS.md)
#
# This program is free software: you can redistribute it and/or modify it under
# the terms of the GNU Affero General Public License as published by the Free
# Software Foundation, either version 3 of the License, or (at your option) any
# later version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE. See the GNU Affero General Public License for more
# details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program. If not, see <https://www.gnu.org/licenses/>.

"""djangosite URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/4.1/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.urls import include, path

urlpatterns = [
    path('', include('listidge.urls')),
]

djangosite/listidge/urls.py
# SPDX-FileCopyrightText: 2023 Galagic Limited, et al. <https://galagic.com>
#
# SPDX-License-Identifier: AGPL-3.0-or-later
#
# Self-hosted lists of any kind: wishlists, task lists, collections and more.
#
# For full copyright information see the AUTHORS file at the top-level
# directory of this distribution or at
# [AUTHORS](https://gitlab.com/thegalagic/listidge/AUTHORS.md)
#
# This program is free software: you can redistribute it and/or modify it under
# the terms of the GNU Affero General Public License as published by the Free
# Software Foundation, either version 3 of the License, or (at your option) any
# later version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE. See the GNU Affero General Public License for more
# details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program. If not, see <https://www.gnu.org/licenses/>.

from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from . import views

app_name = 'listidge'
urlpatterns = [
    path('', views.redirect, name='redirect'),
    path('_admin/lists/', views.lists, name='lists'),
    path('_admin/lists/<int:list_id>/', views.list, name='list'),
    path('_admin/lists/<int:list_id>/delete', views.list_delete,
         name='list_delete'),
    path('_admin/lists/<int:list_id>/<int:item_id>/delete', views.item_delete,
         name='item_delete'),
    path('_admin/lists/<int:list_id>/share', views.list_share_from_list,
         name='list_share_from_list'),
    path('_admin/lists/share/<int:list_id>', views.list_share_from_lists,
         name='list_share_from_lists'),
    path('login/', views.login_user, name='login_user'),
    path('logout/', views.logout_user, name='logout_user'),
    path('<uuid:list_uuid>', views.list_public, name='list_public'),
    path('<uuid:list_uuid>/reserve/<int:item_id>',
         views.item_reserve, name='item_reserve'),
    path('<uuid:list_uuid>/todoupdate/<int:item_id>',
         views.todoitem_update, name='todoitem_update'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
# Note that the above static help function works only in DEBUG mode
# https://docs.djangoproject.com/en/4.1/howto/static-files/#serving-files-uploaded-by-a-user-during-development

if settings.REGISTRATION:
    urlpatterns += path('register/', views.register_user,
                        name='register_user'),

djangosite/listidge/models.py
# SPDX-FileCopyrightText: 2023 Galagic Limited, et al. <https://galagic.com>
#
# SPDX-License-Identifier: AGPL-3.0-or-later
#
# Self-hosted lists of any kind: wishlists, task lists, collections and more.
#
# For full copyright information see the AUTHORS file at the top-level
# directory of this distribution or at
# [AUTHORS](https://gitlab.com/thegalagic/listidge/AUTHORS.md)
#
# This program is free software: you can redistribute it and/or modify it under
# the terms of the GNU Affero General Public License as published by the Free
# Software Foundation, either version 3 of the License, or (at your option) any
# later version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE. See the GNU Affero General Public License for more
# details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program. If not, see <https://www.gnu.org/licenses/>.

from django.db import models
from django.contrib.auth.models import User


class ListType(models.Model):
    name = models.CharField(max_length=200)

    def __str__(self):
        return self.name


class List(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=200)
    description = models.CharField(max_length=200)
    uuid = models.UUIDField(null=True)
    listype = models.ForeignKey(ListType, on_delete=models.CASCADE)

    def __str__(self):
        return self.name


class ListGiftItem(models.Model):
    list = models.ForeignKey(List, on_delete=models.CASCADE)
    name = models.CharField(max_length=200)
    description = models.CharField(max_length=200)
    link = models.CharField(max_length=500)
    amount = models.IntegerField(default=1)
    image = models.ImageField(upload_to='listgift/%Y/%m/%d/', null=True)

    def __str__(self):
        return self.name


class ListToDoItem(models.Model):
    list = models.ForeignKey(List, on_delete=models.CASCADE)
    name = models.CharField(max_length=200)
    description = models.CharField(max_length=200)
    assigned = models.CharField(max_length=200)
    state = models.CharField(max_length=200)
    completed = models.BooleanField()

    def __str__(self):
        return self.name


class ListCollectionItem(models.Model):
    list = models.ForeignKey(List, on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    description = models.CharField(max_length=200)
    link = models.CharField(max_length=500)
    image = models.ImageField(upload_to='listcollection/%Y/%m/%d/', null=True)

    def __str__(self):
        return self.name

djangosite/listidge/forms.py
# SPDX-FileCopyrightText: 2023 Galagic Limited, et al. <https://galagic.com>
#
# SPDX-License-Identifier: AGPL-3.0-or-later
#
# Self-hosted lists of any kind: wishlists, task lists, collections and more.
#
# For full copyright information see the AUTHORS file at the top-level
# directory of this distribution or at
# [AUTHORS](https://gitlab.com/thegalagic/listidge/AUTHORS.md)
#
# This program is free software: you can redistribute it and/or modify it under
# the terms of the GNU Affero General Public License as published by the Free
# Software Foundation, either version 3 of the License, or (at your option) any
# later version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE. See the GNU Affero General Public License for more
# details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program. If not, see <https://www.gnu.org/licenses/>.

from django import forms


class ListWishlistForm(forms.Form):
    name = forms.CharField(max_length=200, required=False)
    description = forms.CharField(max_length=200, required=False)
    link = forms.CharField(max_length=500, required=False)
    amount = forms.IntegerField(min_value=1, max_value=100, required=True)
    image = forms.ImageField(required=False)


class ListCollectionItemForm(forms.Form):
    title = forms.CharField(max_length=200, required=False)
    description = forms.CharField(max_length=200, required=False)
    link = forms.CharField(max_length=500, required=False)
    image = forms.ImageField(required=False)

djangosite/listidge/views.py
# SPDX-FileCopyrightText: 2023 Galagic Limited, et al. <https://galagic.com>
#
# SPDX-License-Identifier: AGPL-3.0-or-later
#
# Self-hosted lists of any kind: wishlists, task lists, collections and more.
#
# For full copyright information see the AUTHORS file at the top-level
# directory of this distribution or at
# [AUTHORS](https://gitlab.com/thegalagic/listidge/AUTHORS.md)
#
# This program is free software: you can redistribute it and/or modify it under
# the terms of the GNU Affero General Public License as published by the Free
# Software Foundation, either version 3 of the License, or (at your option) any
# later version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE. See the GNU Affero General Public License for more
# details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program. If not, see <https://www.gnu.org/licenses/>.

import uuid
from django.conf import settings
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.utils.http import url_has_allowed_host_and_scheme
from django.utils.encoding import iri_to_uri

from .models import List, ListGiftItem, ListType, ListToDoItem
from .listmanagers import get_list_mgr


def check_demo_user(username):
    if settings.DEMO_USER and username == 'demo':
        if not User.objects.filter(username="demo").exists():
            User.objects.create_user("demo", 'lennon@thebeatles.com', "demo")


def redirect(request):
    return HttpResponseRedirect(reverse('listidge:lists'))


def login_user(request):
    # Next parameter need careful processing
    # https://stackoverflow.com/a/64154187/28170
    # https://stackoverflow.com/a/60372947/28170
    paramdict = {"registration": settings.REGISTRATION}

    if settings.DEMO_USER:
        paramdict['demo'] = "True"

    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        check_demo_user(username)

        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            next = request.POST['next']
            if next is None:
                return HttpResponseRedirect(reverse('listidge:lists'))
            elif url_has_allowed_host_and_scheme(
                    url=next,
                    allowed_hosts={request.get_host()},
                    require_https=request.is_secure()):
                return HttpResponseRedirect(iri_to_uri(next))
            else:
                return HttpResponseRedirect(reverse('listidge:lists'))
        else:
            paramdict['error'] = "Login failed"
            return render(request, 'listidge/login.html', paramdict)
    else:
        if 'next' in request.GET:
            paramdict['next'] = request.GET['next']
        return render(request, 'listidge/login.html', paramdict)


def register_user(request):
    if settings.REGISTRATION:
        if request.method == 'POST':
            username = request.POST['username']
            password = request.POST['password']

            if User.objects.filter(username=username).exists():
                return render(request, 'listidge/register.html',
                              {'error': "Username already taken"})

            user = User.objects.create_user(username, 'lennon@thebeatles.com',
                                            password)
            if user is not None:
                login(request, user)
                return HttpResponseRedirect(reverse('listidge:lists'))
            else:
                return HttpResponseRedirect('.')
        else:
            return render(request, 'listidge/register.html')
    else:
        return HttpResponseRedirect('.')


def logout_user(request):
    logout(request)
    return HttpResponseRedirect(reverse('listidge:redirect'))


@login_required
def lists(request):
    if request.method == 'POST':
        lstype = get_object_or_404(ListType, name=request.POST['listype'])
        lst = List(user=request.user,
                   name=request.POST['name'],
                   description=request.POST['description'],
                   listype=lstype)
        lst.save()
        return HttpResponseRedirect('.')
    else:
        lists = List.objects.filter(user=request.user)
        return render(request, 'listidge/lists.html', {'lists': lists})


@login_required
def list(request, list_id):
    lst = List.objects.filter(user=request.user, id=list_id)
    if not lst:
        return render(request, 'listidge/noperm.html')

    lst = get_object_or_404(List, pk=list_id)
    mgr = get_list_mgr(lst)

    if request.method == 'POST':
        (success, errors) = mgr.create_item(request.POST, request.FILES)
        if not success:
            (template, items) = mgr.get_items()
            return render(request, template,
                          {'list': lst, "items": items, "errors": errors})

        return HttpResponseRedirect('.')
    else:
        (template, items) = mgr.get_items()
        return render(request, template,
                      {'list': lst, "items": items})


def list_public(request, list_uuid):
    lst = get_object_or_404(List, uuid=list_uuid)
    mgr = get_list_mgr(lst)
    (template, context) = mgr.get_public_items()
    return render(request, template, context)


@login_required
def list_delete(request, list_id):
    lst = List.objects.filter(user=request.user, id=list_id)
    if not lst:
        return render(request, 'listidge/noperm.html')

    lst = get_object_or_404(List, pk=list_id)
    lst.delete()
    return HttpResponseRedirect(reverse('listidge:lists'))


@login_required
def item_delete(request, list_id, item_id):
    lst = List.objects.filter(user=request.user, id=list_id)
    if not lst:
        return render(request, 'listidge/noperm.html')

    lst = get_object_or_404(List, pk=list_id)
    mgr = get_list_mgr(lst)
    mgr.delete_item(item_id)
    return HttpResponseRedirect(reverse('listidge:list', args=(list_id,)))


@login_required
def list_share_from_list(request, list_id):
    lst = List.objects.filter(user=request.user, id=list_id)
    if not lst:
        return render(request, 'listidge/noperm.html')

    lst = get_object_or_404(List, pk=list_id)
    lst.uuid = uuid.uuid4()
    lst.save()
    return HttpResponseRedirect(reverse('listidge:list', args=(list_id,)))


@login_required
def list_share_from_lists(request, list_id):
    lst = List.objects.filter(user=request.user, id=list_id)
    if not lst:
        return render(request, 'listidge/noperm.html')

    lst = get_object_or_404(List, pk=list_id)
    lst.uuid = uuid.uuid4()
    lst.save()
    return HttpResponseRedirect(reverse('listidge:lists'))


def item_reserve(request, list_uuid, item_id):
    lst = get_object_or_404(List, uuid=list_uuid)
    lgi = get_object_or_404(ListGiftItem, id=item_id)
    lgi.amount -= 1
    lgi.save()
    # Must be a better way to send them back to the public link
    return HttpResponseRedirect(reverse('listidge:list_public',
                                        args=(lst.uuid,)))


def todoitem_update(request, list_uuid, item_id):
    lst = get_object_or_404(List, uuid=list_uuid)
    ltdi = get_object_or_404(ListToDoItem, id=item_id)
    ltdi.state = request.POST['state']
    ltdi.completed = 'completed' in request.POST
    ltdi.save()
    # Must be a better way to send them back to the public link
    return HttpResponseRedirect(reverse('listidge:list_public',
                                        args=(lst.uuid,)))

djangosite/listidge/templates/listidge/list_public.html
<!--
SPDX-FileCopyrightText: 2023 Galagic Limited, et al. <https://galagic.com>

SPDX-License-Identifier: CC-BY-SA-4.0

Self-hosted lists of any kind: wishlists, task lists, collections and more.

For full copyright information see the AUTHORS file at the top-level
directory of this distribution or at
[AUTHORS](https://gitlab.com/thegalagic/listidge/AUTHORS.md)

This work is licensed under the Creative Commons Attribution 4.0 International
License. You should have received a copy of the license along with this work.
If not, visit http://creativecommons.org/licenses/by/4.0/ or send a letter to
Creative Commons, PO Box 1866, Mountain View, CA 94042, USA.
-->

{% extends "listidge/base.html" %}

{% load django_bootstrap5 %}

{% block title %}{{ list.name }}{% endblock %}
{% block content %}
{% load static %}
<nav class="navbar navbar-expand-sm navbar-light bg-light justify-content-between">
  <a class="navbar-brand" href="{% url 'listidge:redirect' %}">
    <img class="mx-auto d-block img-fluid" src="{% static 'listidge/logo.png' %}" alt="Listidge" width="300" height="119">
  </a>
</nav>

<div class="container">
  <div class="row">
    <div class="col-md-3"></div>

    <div class="col-md-6">
      <h1>{{ list.name }}</h1>

      <p>{{ list.description }}</p>

      {% if items %}
        {% for item in items %}
          <div class="card my-3">
            {% if item.image %}
              <img src="{{ item.image.url }}" class="img-fluid rounded">
            {% endif %}
            <div class="card-body">
              {% if item.link %}
                <h2 class="card-title"><a href="{{ item.link }}">{{ item.name }}</a></h2>
              {% else %}
                <h2 class="card-title">{{ item.name }}</h2>
              {% endif %}
              <p class="card-subtitle mb-2 text-muted">{{ item.description }}</p>
              <p class="card-text">{{ item.amount }} wanted.</p>
            </div>
            <div class="card-footer">
              <form class="form-inline flex-row-reverse" action="{% url 'listidge:item_reserve' list.uuid item.id %}" method="post">
                {% csrf_token %}
                <div class="row">
                  <!-- To get right align we have to use cols as we are inside a container
                       https://stackoverflow.com/a/52042069/28170 -->
                  <div class="col"></div>
                  <div class="col-auto">
                    <button type="submit" class="btn btn-danger">Reserve 1</button>
                  </div>
                </div>
              </form>
            </div>
          </div>
        {% endfor %}
      {% else %}
        <div class="alert alert-danger" role="alert">
          This list is empty.
        </div>
      {% endif %}
    </div>

    <div class="col-md-3"></div>

  </div>
</div>

{% endblock %}

djangosite/listidge/templates/listidge/list_public_todo_card.html
<!--
SPDX-FileCopyrightText: 2023 Galagic Limited, et al. <https://galagic.com>

SPDX-License-Identifier: CC-BY-SA-4.0

Self-hosted lists of any kind: wishlists, task lists, collections and more.

For full copyright information see the AUTHORS file at the top-level
directory of this distribution or at
[AUTHORS](https://gitlab.com/thegalagic/listidge/AUTHORS.md)

This work is licensed under the Creative Commons Attribution 4.0 International
License. You should have received a copy of the license along with this work.
If not, visit http://creativecommons.org/licenses/by/4.0/ or send a letter to
Creative Commons, PO Box 1866, Mountain View, CA 94042, USA.
-->
<div class="card my-3">
  <div class="card-body">
    <h3 class="card-title{% if item.completed %} text-decoration-line-through{% endif %}">{{ item.name }}</h3>
    <p class="card-subtitle mb-2 text-muted">{{ item.assigned }}</p>
    <p class="card-text">{{ item.description }}</p>
  </div>
  <div class="card-footer">
    <form class="form-inline flex-row-reverse" action="{% url 'listidge:todoitem_update' list.uuid item.id %}" method="post">
      {% csrf_token %}
      <div class="row">
        <!-- To get right align we have to use cols as we are inside a container
             https://stackoverflow.com/a/52042069/28170 -->
        <div class="col-auto my-1">
          <select class="form-select" id="state" name="state" aria-label="Select state">
            <option {% if item.state == "To Do" %}selected{% endif %}>To Do</option>
            <option {% if item.state == "Doing" %}selected{% endif %}>Doing</option>
            <option {% if item.state == "Done" %}selected{% endif %}>Done</option>
          </select>
        </div>
        <div class="col form-check my-auto mx-3">
          <label for="completed" class="form-check-label">Complete</label>
          <input type="checkbox" class="form-check-input" {% if item.completed %}checked{% endif %} name="completed" id="completed">
        </div>
        <div class="col"></div>
        <div class="col my-1">
          <button type="submit" class="btn btn-secondary">Update</button>
        </div>
      </div>
    </form>
  </div>
</div>

djangosite/listidge/templates/listidge/login.html
<!--
SPDX-FileCopyrightText: 2023 Galagic Limited, et al. <https://galagic.com>

SPDX-License-Identifier: CC-BY-SA-4.0

Self-hosted lists of any kind: wishlists, task lists, collections and more.

For full copyright information see the AUTHORS file at the top-level
directory of this distribution or at
[AUTHORS](https://gitlab.com/thegalagic/listidge/AUTHORS.md)

This work is licensed under the Creative Commons Attribution 4.0 International
License. You should have received a copy of the license along with this work.
If not, visit http://creativecommons.org/licenses/by/4.0/ or send a letter to
Creative Commons, PO Box 1866, Mountain View, CA 94042, USA.
-->

{% extends "listidge/base.html" %}

{% load static %}
{% load django_bootstrap5 %}

{% block title %}Login{% endblock %}
{% block content %}

<div class="container vh-100">
  <form class="container-sm mt-5" action="{% url 'listidge:login_user' %}" method="post" style="max-width: 330px;">
    <img class="mx-auto d-block img-fluid" src="{% static 'listidge/logo.png' %}" alt="" width="300" height="119">
    <h3 class="mb-3 fw-normal text-center">Please sign in</h3>
    {% csrf_token %}
    <div class="alert alert-warning alert-dismissible" role="alert">
      <strong>Caution: </strong>this is a prototype, insecure and unreliable. Data is deleted regularly. Don't enter any private information.
      <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
    {% if error %}
    <div class="alert alert-danger" role="alert">
      {{ error }}
    </div>
    {% endif %}
    {% if demo %}
    <p class="text-center">Login with demo/demo{% if registration %} or <a href="/register">sign up</a>{% endif %}</p>
    {% endif %}
    <div class="form-group my-1">
      <input type="text" class="form-control" name="username" id="username" placeholder="Username" {% if demo %}value="demo" {% endif %}>
    </div>
    <div class="form-group">
      <input type="password" class="form-control" name="password" id="password" placeholder="Password" {% if demo %}value="demo" {% endif %}>
    </div>
    <input type="hidden" name="next" value="{{ next }}">
    <button type="submit" class="w-100 mt-3 btn btn-lg btn-primary">Login</button>
  </form>
  {% if registration %}
    <p class="text-center my-3">Don't have an account? <a href="/register">Sign up</a></p>
  {% endif %}
  <p class="text-center my-3 text-muted">Open source - find us on <a href="https://gitlab.com/thegalagic/listidge">GitLab</a></p>
</div>
{% endblock %}

djangosite/listidge/templates/listidge/nav.html
<!--
SPDX-FileCopyrightText: 2023 Galagic Limited, et al. <https://galagic.com>

SPDX-License-Identifier: CC-BY-SA-4.0

Self-hosted lists of any kind: wishlists, task lists, collections and more.

For full copyright information see the AUTHORS file at the top-level
directory of this distribution or at
[AUTHORS](https://gitlab.com/thegalagic/listidge/AUTHORS.md)

This work is licensed under the Creative Commons Attribution 4.0 International
License. You should have received a copy of the license along with this work.
If not, visit http://creativecommons.org/licenses/by/4.0/ or send a letter to
Creative Commons, PO Box 1866, Mountain View, CA 94042, USA.
-->

{% load static %}
<nav class="navbar navbar-expand-sm navbar-light bg-light justify-content-between">
  <a class="navbar-brand flex-grow-1" href="{% url 'listidge:redirect' %}">
    <img class="d-block img-fluid" src="{% static 'listidge/logo.png' %}" alt="Listidge" width="300" height="119">
  </a>
  <p class="my-auto mx-3">Find us on <a href="https://gitlab.com/thegalagic/listidge">GitLab</a></p>
  <a href="{% url 'listidge:logout_user' %}" class="btn btn-outline-secondary btn-lg m-3" role="button">Logout {{ user.username }}</a>
</nav>
<nav class="bg-light" aria-label="breadcrumb">
  <ol class="breadcrumb mx-3 p-3">
    {% if lists %}
      <li class="breadcrumb-item active" aria-current="page"><h5>Lists</h5></li>
    {% else %}
    <li class="breadcrumb-item"><a href="{% url 'listidge:lists' %}"><h5>Lists</h5></a></li>
    <li class="breadcrumb-item active" aria-current="page"><h5>{{ list.name }}</h5></li>
    {% endif %}
  </ol>
</nav>

djangosite/listidge/templates/listidge/noperm.html
<!--
SPDX-FileCopyrightText: 2023 Galagic Limited, et al. <https://galagic.com>

SPDX-License-Identifier: CC-BY-SA-4.0

Self-hosted lists of any kind: wishlists, task lists, collections and more.

For full copyright information see the AUTHORS file at the top-level
directory of this distribution or at
[AUTHORS](https://gitlab.com/thegalagic/listidge/AUTHORS.md)

This work is licensed under the Creative Commons Attribution 4.0 International
License. You should have received a copy of the license along with this work.
If not, visit http://creativecommons.org/licenses/by/4.0/ or send a letter to
Creative Commons, PO Box 1866, Mountain View, CA 94042, USA.
-->

{% extends "listidge/base.html" %}

{% load django_bootstrap5 %}

{% block title %}{{ list.name }}{% endblock %}
{% block content %}

{% include "listidge/nav.html" %}

<div class="container">
  <div class="row">
    <div class="alert alert-danger" role="alert">
      You don't own that list.
    </div>
  </div>
</div>

{% endblock %}

djangosite/listidge/templates/listidge/register.html
<!--
SPDX-FileCopyrightText: 2023 Galagic Limited, et al. <https://galagic.com>

SPDX-License-Identifier: CC-BY-SA-4.0

Self-hosted lists of any kind: wishlists, task lists, collections and more.

For full copyright information see the AUTHORS file at the top-level
directory of this distribution or at
[AUTHORS](https://gitlab.com/thegalagic/listidge/AUTHORS.md)

This work is licensed under the Creative Commons Attribution 4.0 International
License. You should have received a copy of the license along with this work.
If not, visit http://creativecommons.org/licenses/by/4.0/ or send a letter to
Creative Commons, PO Box 1866, Mountain View, CA 94042, USA.
-->

{% extends "listidge/base.html" %}

{% load static %}
{% load django_bootstrap5 %}

{% block title %}Register{% endblock %}
{% block content %}

<div class="container vh-100">
  <form class="container-sm mt-5" action="{% url 'listidge:register_user' %}" method="post" style="max-width: 330px;">
    <img class="mx-auto d-block img-fluid" src="{% static 'listidge/logo.png' %}" alt="" width="300" height="119">
    <h3 class="mb-3 fw-normal text-center">Create your account</h3>
    {% csrf_token %}
    <div class="alert alert-warning alert-dismissible" role="alert">
      <strong>Caution: </strong>this is a prototype, insecure and unreliable. Data is deleted regularly. Don't enter any private information.
      <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
    {% if error %}
    <div class="alert alert-danger" role="alert">
      {{ error }}
    </div>
    {% endif %}
    <div class="form-group my-1">
      <input type="text" class="form-control" name="username" id="username" placeholder="Username">
    </div>
    <div class="form-group">
      <input type="password" class="form-control" name="password" id="password" placeholder="Password">
    </div>
    <button type="submit" class="w-100 mt-3 btn btn-lg btn-primary">Register</button>
  </form>
  <p class="text-center my-3">Already have an account? <a href="/login">Sign in</a></p>
  <p class="text-center my-3 text-muted">Open source - find us on <a href="https://gitlab.com/thegalagic/listidge">GitLab</a></p>
</div>
{% endblock %}